version: '3'

volumes:
    postgres_volume:
    redis_volume:

services:
    postgresql:
        image: postgres:14-alpine3.17
        ports:
            - '15432:5432'
        env_file:
            - .env
        volumes:
            - postgres_volume:/var/lib/postgresql/data
    redis:
        image: redis:7.4-alpine
        ports:
            - '16379:6379'
        volumes:
            - redis_volume:/data
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_USER=${REDIS_USER}
            - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
