version: '3'

volumes:
    postgres_volume:

services:
    postgresql:
        image: postgres:14-alpine3.17
        ports:
            - '25432:5432'
        env_file:
            - .env
        volumes:
            - postgres_volume:/var/lib/postgresql/data
